# .sops.yaml

keys:
  - &primary age1xs9geh2zavxhasq3purqxgyjwswngrq7xqpqpcayvfdfft0deqxqyeld4e
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
