# .sops.yaml

keys:
  - &primary age1u5hueex8cgfvlds97l7t8lynlcf20mrqujnx0glfxyg06sz5dgjsf85cun
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
          - *primary
