services:
  glance:
    container_name: glance
    image: glanceapp/glance
    restart: unless-stopped
    volumes:
      - ./:/app/config
    ports:
      - 8080:8080
    environment:
      - UPTIME_KUMA_URL=https://kuma.homelab.gothuey.dev
      - UPTIME_KUMA_STATUS_SLUG=containers
