- Media:
    - Jellyfin:
        icon: jellyfin.svg
        href: http://192.168.1.2:8096
        description: Watch Movies & TV Shows
        widget:
          type: jellyfin
          url: http://192.168.1.2:8096
          key: "{{HOMEPAGE_FILE_JELLYFIN_KEY}}"

- Services:
    - Synology Photos:
        icon: synology-photos.png
        href: https://nas.homelab.gothuey.dev/?launchApp=SYNO.Foto.AppInstance

- System:
    - Grafana:
        icon: grafana.png
        href: http://192.168.1.5:2342
        statusStyle: dot
        description: Monitoring dashboards
        widget:
            type: grafana
            url: http://192.168.1.5:2342
            fields: ["dashboards","datasources"]
            username: admin
            password: "{{HOMEPAGE_FILE_GRAFANA_KEY}}"

- Server:
    - Info:
        widget:
          type: glances
          version: 4
          url: http://192.168.1.5:61208
          metric: info
    - Process:
        widget:
          type: glances
          version: 4
          url: http://192.168.1.5:61208
          metric: process
          chart: ifn
