- Media: []

- Services:
  - Synology Photos:
        icon: synology-photos.png
        href: https://nas.homelab.gothuey.dev/?launchApp=SYNO.Foto.AppInstance

- System: []

# - Server: FIXME: Currently returns a 500 error
#     - Info:
#         widget:
#           type: glances
#           url: http://host.containers.internal:61208
#           metric: info
#     - CPU Temp:
#         widget:
#           type: glances
#           url: http://host.containers.internal:61208
#           metric: sensor:Tctl
#     - Storage:
#         widget:
#           type: glances
#           url: http://host.containers.internal:61208
#           metric: process
#     - Network:
#         widget:
#           type: glances
#           url: http://host.containers.internal:61208
#           metric: network:enp1s0f0
#           chart: true