- Media: []

- Services:
    - Synology Photos:
        icon: synology-photos.png
        href: https://nas.homelab.gothuey.dev/?launchApp=SYNO.Foto.AppInstance

- System: []

- Server:
    - Info:
        widget:
          type: glances
          version: 4
          url: http://192.168.1.5:61208
          metric: info
    - Process:
        widget:
          type: glances
          version: 4
          url: http://192.168.1.5:61208
          metric: process
          chart: ifn
