name: build

on:
  push:
  workflow_dispatch:

jobs:
  pre-commit:
    name: ✅ pre-commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1

  nix:
    name: 🧪 nix validations
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v31

      - name: nix flake check
        run: nix flake check
